### PR TITLE
#168781670 Setting up dotenv

### PR DESCRIPTION
**Pull request by nignanthomas**
#### What does this PR do?
Setup dotenv

#### Description of Task to be completed?
- Import dotenv module to src/index.js
- Call dotenv.config for the app to use environment variables

#### How should this be manually tested?
- Clone the repository from [here](https://github.com/andela/caret-bn-backend.git)
- Browse to the repo directory
- Run `npm install`
- Explore the ***src/index.js*** file and ***.env.example***

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#168781670](https://www.pivotaltracker.com/story/show/168781670)

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

### CODE REVIEW

**Review by Cheza-Dzabala — CHANGES_REQUESTED** [review]
I'm not sure if you should set up any of the environment variables in the .env.example yet. I believe that they will be added as the chores & features each gets done. Like the JWT and the Database variables. Allow the people setting up those chores to dictate the variable names.

**Review by alainmateso — CHANGES_REQUESTED** [review]
I would like to ask why is the `.env.example` file(replica for .env file) inside the `src` folder?  Because I think the .env file should be in the root of the directory.

**Comment by nignanthomas** [comment]
> I would like to ask why is the `.env.example` file(replica for .env file) inside the `src` folder? Because I think the .env file should be in the root of the directory.

True, it should be in the root. I'm on it

**Review by alainmateso — APPROVED** [review]
Looks great!

**Review by sabin18 — APPROVED** [review]
looks good

**Review by Cheza-Dzabala — APPROVED** [review]
cool

**Pull request merged**
