### PR TITLE
#168781667 Setup Unit Testing

### PR DESCRIPTION
**Pull request by sabin18**
#### What does this PR do?
- setup unit testing  To ensure the back end has all functionality working as intended.
#### Description of Task to be completed
  
- I have installed Mocha as the test runner and chai and chai-http for the unit tests.
- I added test script in package.json.

#### How should this be manually tested?
- clone the repository : git clone https://github.com/andela/caret-bn-backend.git
- checkout to branch ch-setting-test-168781667
- do npm run test

#### Any background context you want to provide?
    `N/A`
#### What are the relevant pivotal tracker stories?
[#68781667](https://www.pivotaltracker.com/n/projects/2400651)

#### Screenshots (if appropriate)

Screen Shot 2019-10-02 at 12 45 36

####  Questions:
   `N/A`

### CODE REVIEW

**Review by alainmateso — CHANGES_REQUESTED** [review]
Please add a body to your commit message!

**Review by nignanthomas — CHANGES_REQUESTED** [review]
Regarding the implementation of the chore, I think it is okay, but I am expecting you to run a mock test to ensure the test script is running mocha.
My concern is also with the body of the PR:
**How has it been tested** I might need some explanation about the end to end testing
**JIRA** change JIRA to PT since that is the Project Management Software we are using
Ande make that Strory ID clickable like this [#168781667](https://www.pivotaltracker.com/story/show/168781667)

**Review by ngireric123 — APPROVED** [review]

**Review by nakiwuge — CHANGES_REQUESTED** [review]
@sabin18 good job so far but please add some tests so that we can test the functionality

**Review by nignanthomas — APPROVED** [review]

**Review by Cheza-Dzabala — APPROVED** [review]
everything seems in order

**Review by alainmateso — APPROVED** [review]

**Review by ngireric123 — APPROVED** [review]
it is good now

**Review by nakiwuge — APPROVED** [review]

**Pull request merged**
