### PR TITLE
#168781666 Integrate Travis CI

### PR DESCRIPTION
**Pull request by alainmateso**
#### What does this PR do?
- Integrates Travis CI
- Adds README badge for build

#### Description of Task to be completed?

- Add caret-bn-backend repo to travis-ci.org
- Add .travis.yml file
- Add build README badge

#### How should this be manually tested?

- Clone the repository from [here](https://github.com/andela/caret-bn-backend.git)
- Browse to the repo directory
- Run `npm install`
- Preview README file

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#168781666
#### Screenshots (if appropriate)
Screen Shot 2019-10-01 at 13 09 11

#### Questions:
N/A

### CODE REVIEW

**Review by Cheza-Dzabala — CHANGES_REQUESTED** [review]
Please rebase your branch and pull another PR

**Review by nignanthomas — APPROVED** [review]
Awesome job @alainmateso 👍

**Review by Cheza-Dzabala — APPROVED** [review]
AWESOME!!

**Review by sabin18 — APPROVED** [review]
Good job alain .

**Pull request merged**
